### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
49 tests run in less than 3/10ths of a second...
* Results at https://github.com/Shrutikabansal/python_unit_test/actions

https://github.com/cclauss/python_unit_test/runs/576376205?check_suite_focus=true#step:10:6
```
============================= test session starts =============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/runner/work/python_unit_test/python_unit_test
collected 49 items

test_basic.py .                                                          [  2%]
test_for_string.py .....                                                 [ 12%]
CalculatorTest/test_calcu.py ..................................          [ 81%]
CalculatorTest/test_calcu_parametrize.py ...                             [ 87%]
CalculatorTest/test_string_calc.py ..                                    [ 91%]
employ/test_employ.py ....                                               [100%]

============================== 49 passed in 0.30s =============================
```

### CODE REVIEW

**Comment by Shrutikabansal** [comment]
I am new in this, May i know how it makes better

**Comment by Shrutikabansal** [comment]
How it helps?

**Comment by cclauss** [comment]
It runs automated tests to see if misspelled words have been added to README.md or Python syntax errors have been added to the code.  https://github.com/cclauss/python_unit_test/actions

**Comment by Shrutikabansal** [comment]
Thank you for making it much meaningful

**Pull request merged**
